version: '2'
services:
  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    image: jonbrouse/elk:elasticsearch-sysadvent
    build: elasticsearch
    command: -Des.insecure.allow.root=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/volumes/esdata/:/opt/elasticsearch/data
      - ./elasticsearch/assets/elasticsearch.yml:/opt/elasticsearch/config/elasticsearch.yml
  logstash:
    hostname: logstash
    container_name: logstash
    image: jonbrouse/elk:logstash-sysadvent
    build: logstash
    ports:
      - "24642:24642"
    command: -f /etc/logstash.conf 
    tty: true
    volumes:
      - ./logstash/assets/logstash.conf:/etc/logstash.conf
    links:
      - elasticsearch
  kibana:
    hostname: kibana
    container_name: kibana
    image: jonbrouse/elk:kibana-sysadvent
    build: kibana
    links:
      - elasticsearch
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx:stable-alpine
    links:
      - kibana
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/assets/certs:/etc/nginx/certs
      - ./nginx/assets/nginx.conf:/etc/nginx/nginx.conf
